# Generated by Django 3.2.13 on 2022-08-26 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classesmodules', '0002_alter_class_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classesmodules.module'),
        ),
    ]
