# Generated by Django 3.2.13 on 2022-08-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classesmodules', '0003_alter_class_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
