services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teste_verzel
  api:
    build: .
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
  wait:
    image: waisbrot/wait
    environment:
      - TARGETS=postgres:5432,api:8000

volumes:
  postgres-db-volume:
