services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teste_verzel
  wait:
    image: waisbrot/wait
    environment:
      - TARGETS=postgres:5432

volumes:
  postgres-db-volume:
